### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by joeybaker** [sullenor/css-modules-require-hook#2]
It would be great to have this on npm!

**Comment by sullenor** [comment]
Hi, @joeybaker 

Thank you for your reminder. Finally, I have succeeded at making independent version from `css-modules-loader-core` and its almost ready to be published :)
I Just need to fix few tests first, which affect some part of CSSI implementation.

Sorry to keep you, I hope, I'll finish it in few days.

**Comment by joeybaker** [comment]
:)

**Comment by sullenor** [comment]
done! :)
