### ISSUE TITLE
Set postcss deps as peerDeps?

### ISSUE THREAD

**Issue by joeybaker** [sullenor/css-modules-require-hook#5]
It might be cleaner to have all the postcss deps as peerDeps? That way users of this module can set their own versions.

**Comment by sullenor** [comment]
Aren't peerDeps deprecated in npm? I heard, they are going to remove it completely in the npm v3.0.0

**Comment by joeybaker** [comment]
well… no. They're not removed, they're changing behavior. In npm 2, peerDeps were auto-installed, and installs broke when this auto-install failed. In npm 3, peerDeps aren't auto-installed. It's up to the user to install the version they want.

**Comment by sullenor** [comment]
Well, I lack information about the topic, so I don't to know to what possible problems that solution can lead. Let me think a little about it.

Currently, I want to fix test, so it will be possible to publish it. After that, I'll look on it closely.

**Comment by nkbt** [comment]
You should definitely use peerDeps, they work fine and they will for even better.

**Comment by sullenor** [comment]
I have to agree with you. Having postcss and its plugins as peerDeps is a good idea. It will be convenient both for the user and for maintainer (less updates).
I read npm documentation and made few tests with npm@3.2.2 and presumably it works well.

Documentation:
- https://docs.npmjs.com/files/package.json#peerdependencies
- https://github.com/npm/npm/releases/tag/v3.0.0

pr: https://github.com/sullenor/css-modules-require-hook/pull/12

**Comment by sullenor** [comment]
I published update, so you may try to use it :)
Version [1.0.2](https://github.com/sullenor/css-modules-require-hook/releases/tag/1.0.2)
