### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by sullenor** [sullenor/css-modules-require-hook#7]
Just thought about adding jscs and eslint. Also add scripts to lint files on the precommit hook and globally.

**Comment by nkbt** [comment]
I can take this one. Been doing this stuff for a while now for different projects.

**Comment by sullenor** [comment]
I would appreciate if you can make this one!

**Comment by nkbt** [comment]
Awesome. Will make a PR later today then.

**Comment by nkbt** [comment]
@sullenor see #8

**Comment by sullenor** [comment]
:+1:
